model:
  name: "dpad_test"
  nx: 2  # Minimal latent dimensions
  n1: 1  # Minimal behavior-prioritized dimensions
  
  # Simplest DPAD configuration - fully linear (like PSID)
  method_code: "DPAD"  # No nonlinearity, no hidden layers
  epochs: 10  # Very few epochs just to test
  
  # Forecasting
  forecast:
    m: 5  # Small forecast horizon

data:
  root: "resampled_recordings/participants_at_150Hz"
  participant: "PDI1"
  session: "2"
  blocks: [1]  # Just one block for speed
  preprocess: true
  channels:
    is_neural_behavioral: true  # Simpler than neural-to-neural
    input: ["LFP_1"]  # Single input channel
    output: ["tracing_speed"]  # Single output channel
  split:
    within_session_split: true
    train: 0.7
    val: 0.15
    test: 0.15
    min_train_epochs: 10
  batch_size: 32
  sampling_frequency: 150

results:
  save_dir: "results/{model.name}"
  log_dir: "{results.save_dir}/logs"
  checkpoint_dir: "checkpoints"