model:
  name: "dpad_neural"
  nx: 4  # Total latent dimensions
  n1: 0  # No behavior-prioritized dimensions (behavior-agnostic baseline)
  
  # DPAD-specific parameters
  method_code: "DPAD_uAKCzCy2HL128U"  # Fully nonlinear with 2 hidden layers, 128 units
  epochs: 2500
  block_samples: 128
  
  # Forecasting
  forecast:
    m: 1000

data:
  root: "resampled_recordings/participants_at_150Hz"
  participant: "PDI1"
  session: "2"
  blocks: [1, 2, 3, 4, 5]
  preprocess: true
  channels:
    is_neural_behavioral: false  # Neural-to-neural only
    input: ["LFP_1", "LFP_2"]  # Y (input neural)
    output: ["ECOG_1", "ECOG_2", "ECOG_3", "ECOG_4"]  # Predict ECoG from LFP
  split:
    within_session_split: true
    train: 0.6
    val: 0.2
    test: 0.2
    min_train_epochs: 50
  batch_size: 32
  sampling_frequency: 150

results:
  save_dir: "results/{model.name}"
  log_dir: "{results.save_dir}/logs"
  checkpoint_dir: "checkpoints"
