model:
  name: "psid_neural"
  nx: 1
  n1: 0
  i: 5
  time_first: True
  remove_mean_Y: False
  remove_mean_Z: False
  zscore_Y: False
  zscore_Z: False

data:
  root: "resampled_recordings/participants"
  participant: "PDI1"
  session: "2"
  blocks: [1, 2]
  preprocess: true
  channels:
    is_neural_behavioral: false
    input: ["LFP_12"] # Y
    output: None # Z
  split:
    within_session_split: true
    train: 0.6
    val: 0.2
    test: 0.2
    min_train_epochs: 50
  batch_size: 32
  prefetch: 4           # Combines num_workers and shuffle into simpler terms

results:
  save_dir: "results/{model.name}"
  log_dir: "{results.save_dir}/logs"
  checkpoint_dir: "checkpoints"