model:
  name: "psid_neural"
  nx: 1
  n1: 0
  i: 5
  time_first: true
  remove_mean_Y: false
  remove_mean_Z: false
  zscore_Y: false
  zscore_Z: false
  forecast:
    m: 1000

data:
  root: "resampled_recordings/participants_2"
  participant: "PDI1"
  session: "2"
  blocks: [1, 2, 3, 4, 5]
  preprocess: true
  channels:
    is_neural_behavioral: false
    input: ["LFP_12"] # Y
    output: None # Z
  split:
    within_session_split: true
    train: 0.6
    val: 0.2
    test: 0.2
    min_train_epochs: 50
  batch_size: 32

results:
  save_dir: "results/{model.name}"
  log_dir: "{results.save_dir}/logs"
  checkpoint_dir: "checkpoints"