model:
  name: "psid_behavioral"
  nx: 4
  n1: 2
  i: 5
  time_first: true
  remove_mean_Y: false
  remove_mean_Z: false
  zscore_Y: false
  zscore_Z: false
  forecast:
    m: 1 # seconds

data:
  root: "resampled_recordings/participants_at_150Hz"
  participant: "PDI1"
  session: "2"
  blocks: [1, 2, 3, 4, 5]
  preprocess: true
  channels:
    is_neural_behavioral: true
    input: ["ECOG_1", "ECOG_2", "ECOG_3", "ECOG_4"] # Y
    output: ["tracing_speed"] # Z
  split:
    within_session_split: true
    train: 0.6
    val: 0.2
    test: 0.2
    min_train_epochs: 50
  batch_size: 32
  sampling_frequency: 150
  dbs_condition: "off"

results:
  save_dir: "results/{model.name}"
  log_dir: "{results.save_dir}/logs"
  checkpoint_dir: "checkpoints"