model:
  name: "##" # Model name
  nx: ## # Total latent dimensions
  n1: ## # Behavior-prioritized latent dimensions
  i: ## # Input dimensions
  time_first: ## # Boolean
  remove_mean_Y: ## # Boolean
  remove_mean_Z: ## # Boolean
  zscore_Y: ## # Boolean
  zscore_Z: ## # Boolean
  forecast:
    m: ## # Number of steps to forecast

data:
  root: "##" # Root directory for data
  participant: "##" # Participant ID
  session: "##" # Session ID
  blocks: [##] # Blocks to use or all the blocks as string "all"
  preprocess: ## # Boolean
  channels:
    is_neural_behavioral: ## # Boolean
    input: [##] # Y
    output: [##] # Z
  split:
    within_session_split: ## # Boolean
    train: ## # Proportion of data to use for training
    val: ## # Proportion of data to use for validation
    test: ## # Proportion of data to use for testing
    min_train_epochs: ## # Minimum number of epochs to train for
  batch_size: ## # Batch size for training
  sampling_frequency: ## # Sampling frequency of the data
  dbs_condition: ## # Options: "on", "off", "both"

results:
  save_dir: "results/{model.name}" # Directory for saving results
  log_dir: "{results.save_dir}/logs" # Directory for logging
  checkpoint_dir: "checkpoints" # Directory for saving checkpoints